# Generated by Django 3.2 on 2024-02-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGeo', '0002_auto_20240128_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='sitio'),
        ),
    ]
