# Generated by Django 3.2 on 2024-02-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGeo', '0004_auto_20240209_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='latitud',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='longitud',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
