# Generated by Django 3.2 on 2024-02-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGeo', '0005_auto_20240210_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
